import { Metadata } from 'next';
import Navigation from '../components/nav';
import Footer from '../components/footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
export default function GeneralLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <section>
      <Navigation />
      {children}
      <Footer />
    </section>
  );
}
